hyperskill_project:
  id: 131
  ide_files: https://stepik.org/media/attachments/lesson/415777/additional_files.json
  is_template_based: false
  use_ide: true
update_date: Mon, 13 Sep 2021 09:01:43 UTC
stages:
- id: 697
  step: 11042
  is_completed: true
- id: 698
  step: 11043
  is_completed: true
- id: 699
  step: 11044
  is_completed: false
- id: 700
  step: 11045
  is_completed: false
- id: 701
  step: 11046
  is_completed: false
- id: 702
  step: 11047
  is_completed: false
topics:
  0:
  - title: The concept of patterns
    theory_id: 3611
  - title: World Wide Web
    theory_id: 6633
  - title: HyperText Transfer Protocol
    theory_id: 6569
  - title: Introduction to operating systems
    theory_id: 9704
  - title: Introduction to Django
    theory_id: 6277
  - title: Django MVC
    theory_id: 15548
  - title: Django project structure
    theory_id: 6285
  - title: Introduction to databases
    theory_id: 8497
  - title: What is SQL
    theory_id: 7054
  - title: Django ORM
    theory_id: 6832
  - title: Computer programming
    theory_id: 8739
  - title: Introduction to OOP
    theory_id: 3614
  - title: Inheritance
    theory_id: 9844
  - title: Introduction to Python
    theory_id: 5204
  - title: Overview of the basic program
    theory_id: 5208
  - title: Multi-line programs
    theory_id: 5233
  - title: PEP 8
    theory_id: 5879
  - title: Comments
    theory_id: 6081
  - title: Naming variables
    theory_id: 5885
  - title: Taking input
    theory_id: 5913
  - title: Program with numbers
    theory_id: 5872
  - title: If statement
    theory_id: 5953
  - title: Else statement
    theory_id: 5932
  - title: Load module
    theory_id: 6019
  - title: Create module
    theory_id: 6057
  - title: Packages
    theory_id: 6384
  - title: Class
    theory_id: 6661
  - title: Class instances
    theory_id: 6669
  - title: Methods
    theory_id: 6931
  - title: Methods and attributes
    theory_id: 6981
  - title: Magic methods
    theory_id: 7139
  - title: Inheritance
    theory_id: 7235
  - title: Datetime module
    theory_id: 7324
  - title: Data and object mapping
    theory_id: 8262
  - title: Libraries
    theory_id: 8504
  - title: Frameworks
    theory_id: 6701
  - title: Web development
    theory_id: 13931
  - title: Command line overview
    theory_id: 8977
  - title: Parameters and options
    theory_id: 9746
  - title: Pip
    theory_id: 6230
  - title: Virtual Environment
    theory_id: 13923
  - title: Object-Relational Mapping (ORM)
    theory_id: 8312
  - title: Basic data types
    theory_id: 5852
  - title: Integer arithmetic
    theory_id: 5865
  - title: Quotes and multi-line strings
    theory_id: 5814
  - title: Variables
    theory_id: 5859
  - title: String formatting
    theory_id: 6037
  - title: List
    theory_id: 5979
  - title: Invoking a function
    theory_id: 5891
  - title: Declaring a function
    theory_id: 5900
  - title: Scopes
    theory_id: 6322
  - title: Boolean logic
    theory_id: 6025
  - title: Comparisons
    theory_id: 5920
  1:
  - title: Immutability
    theory_id: 7929
  - title: HTTP URL
    theory_id: 6740
  - title: HTTP messages
    theory_id: 6752
  - title: HTML basics
    theory_id: 6434
  - title: Tags and attributes
    theory_id: 7536
  - title: HTML page structure
    theory_id: 6491
  - title: Inline Elements
    theory_id: 7518
  - title: File types
    theory_id: 13017
  - title: Starting a project
    theory_id: 15547
  - title: Launching web server
    theory_id: 6651
  - title: Processing requests
    theory_id: 6472
  - title: Django template language
    theory_id: 6391
  - title: Rendering templates
    theory_id: 8754
  - title: Regexps basics
    theory_id: 7580
  - title: What is a bug
    theory_id: 5504
  - title: Polymorphism
    theory_id: 10027
  - title: Program execution
    theory_id: 6047
  - title: For loop
    theory_id: 6065
  - title: Errors
    theory_id: 6052
  - title: Exceptions
    theory_id: 6042
  - title: Method overriding
    theory_id: 7629
  - title: Escape sequences
    theory_id: 7130
  - title: Indexes
    theory_id: 6189
  - title: Basic string methods
    theory_id: 6842
  - title: Identity testing
    theory_id: 8077
  - title: Dictionary
    theory_id: 6481
  - title: Arguments
    theory_id: 7248
  - title: Operations with list
    theory_id: 6031
  - title: Tuple
    theory_id: 7462
  - title: Dictionary methods
    theory_id: 9008
  - title: Operations with dictionary
    theory_id: 11096
  - title: Objects in Python
    theory_id: 9262
  - title: Default arguments
    theory_id: 10295
  - title: Args
    theory_id: 8560
  - title: Kwargs
    theory_id: 9544
  - title: Split and join
    theory_id: 6972
  2:
  - title: Queries and filters
    theory_id: 7005
  - title: Built-in exceptions
    theory_id: 11680
  - title: Exception handling
    theory_id: 6270
  3:
  - title: Domains
    theory_id: 6911
  - title: Block-level elements
    theory_id: 7271
  - title: What is CSS
    theory_id: 7678
  - title: HTML attributes id and class
    theory_id: 7527
  - title: HTML forms
    theory_id: 6560
  - title: Submitting data
    theory_id: 7332
  - title: Forms and validation
    theory_id: 7647
  - title: Registration and authentication
    theory_id: 7752
  4:
  - title: Files
    theory_id: 13025
  - title: JSON
    theory_id: 6854
  - title: os module
    theory_id: 11119
  5:
  - title: Design principles
    theory_id: 8956
